version: '3.8'
services:
  web:
    build: .
    ports:
      - "6000:6000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=webserver_db
      - MYSQLCLIENT_CFLAGS=-I/usr/include/mysql
      - MYSQLCLIENT_LDFLAGS=-L/usr/lib/mysql
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=webserver_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

volumes:
  mysql_data:

